spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    openai:
      chat:
        options:
          model: text-embedding-ada-002
      vectorstore:
        pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536